### ISSUE TITLE
A question about data splits.

### ISSUE THREAD

**Issue by chaochao42** [CVMI-Lab/DARS#5]
Hi! Thank you for your remarkable work!

I have a question about the data splits. In previous semi-supervised semantic segmentation papers, there are extremely few labeled data like 92 labeled images in VOC 2012 and 1/30 labeled images in cityscapes. I wonder if your method works in these data splits since the class distribution estimated from such few labeled data may be very inaccurate?

**Comment by RuiFeiHe** [comment]
Hi, thanks for your attention! 

We have not tried these extreme data splits, but it would be interesting for you to explore the limit.

Indeed, the class distribution estimated from such few labeled data could be quite inaccurate. And our limitation is that we rely on knowing the class distribution.

There are a few ways to resolve this, though. For example, there are a few recent works on estimating the class distribution, like "Detecting and Correcting for Label Shift with Black Box predictors". Moreover, for practical usage in industries, there is usually a certain budget to label a medium-size dataset, which we believe would be sufficient to estimate the class distribution.
